import type { Application, Request, Response } from 'express'
import swaggerUi from 'swagger-ui-express'
import * as swaggerDocument from '@/generated/swagger.json'

const customSwaggerCss = `
  .swagger-ui .topbar { display: none; }
  .swagger-ui .info { margin: 25px 0; }
  .swagger-ui .info .title {
    color: #0f172a;
    font-weight: 700;
  }
  .swagger-ui .scheme-container {
    background: #f8fafc;
    border-radius: 8px;
    padding: 15px;
    box-shadow: none;
    border: 1px solid #e2e8f0;
    margin-bottom: 20px;
  }
  .swagger-ui .opblock {
    border-radius: 6px;
    box-shadow: 0 1px 3px rgba(0,0,0,0.05);
  }
`

/**
 * Mounts Swagger UI and OpenAPI JSON endpoints generated by tsoa on the Express application.
 */
export const setupSwaggerDocs = (app: Application): void => {
  const docPaths = ['/docs', '/api-docs']

  // Handle CSP headers specifically for Swagger UI routes so scripts/styles load smoothly alongside Helmet.
  app.use(docPaths, (_req: Request, res: Response, next) => {
    res.setHeader(
      'Content-Security-Policy',
      "default-src 'self'; script-src 'self' 'unsafe-inline' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' https: data:;",
    )
    next()
  })

  // Serve raw OpenAPI JSON specification
  const sendSpec = (_req: Request, res: Response) => {
    res.setHeader('Content-Type', 'application/json')
    res.status(200).send(swaggerDocument)
  }

  app.get('/docs.json', sendSpec)
  app.get('/api-docs.json', sendSpec)
  app.get('/docs/json', sendSpec)

  const uiOptions = {
    customCss: customSwaggerCss,
    customSiteTitle: 'StockPros API Documentation',
    swaggerOptions: {
      persistAuthorization: true,
      displayRequestDuration: true,
      filter: true,
      tagsSorter: 'alpha',
    },
  }

  // Mount Swagger UI on /docs and /api-docs
  app.use('/docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument, uiOptions))
  app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument, uiOptions))
}
