import config from '@/config'
import type { Application, Request, Response } from 'express'
import path from 'path'
import swaggerUi from 'swagger-ui-express'

/**
 * Loads the OpenAPI 3.0 spec generated by `tsoa spec`.
 * Run `npx tsoa spec` to regenerate after adding/modifying controllers in src/docs/controllers/.
 */
const loadSpec = (): Record<string, unknown> => {
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const spec = require(path.join(__dirname, '../../../docs/generated/swagger.json')) as Record<string, unknown>

  // Patch servers at runtime so the local port is always correct
  spec['servers'] = [
    {
      url: `http://localhost:${config.server.port}`,
      description: 'Local Development Server',
    },
  ]

  return spec
}

export const swaggerSpec = loadSpec()

/**
 * Custom CSS giving Swagger UI a polished, dark-themed developer experience matching the StockPros brand.
 */
const customSwaggerCss = `
  .swagger-ui .topbar {
    background-color: #0f172a;
    border-bottom: 1px solid #1e293b;
    padding: 10px 0;
  }
  .swagger-ui .topbar a {
    display: flex;
    align-items: center;
  }
  .swagger-ui .topbar .topbar-wrapper img {
    content: url('https://weyddqoxrfdtgmbcnzew.supabase.co/storage/v1/object/public/public-assets/stockpros-logo.png');
    height: 38px;
    width: auto;
  }
  .swagger-ui .info {
    margin: 25px 0;
  }
  .swagger-ui .info .title {
    color: #0f172a;
    font-weight: 700;
  }
  .swagger-ui .scheme-container {
    background: #f8fafc;
    border-radius: 8px;
    padding: 15px;
    box-shadow: none;
    border: 1px solid #e2e8f0;
    margin-bottom: 20px;
  }
  .swagger-ui .opblock {
    border-radius: 6px;
    box-shadow: 0 1px 3px rgba(0,0,0,0.05);
  }
`

/**
 * Mounts Swagger UI and OpenAPI JSON endpoints on the Express application.
 * The spec is generated by tsoa from src/docs/controllers/ — run `npm run tsoa:spec` to regenerate.
 */
export const setupSwaggerDocs = (app: Application): void => {
  const docPaths = ['/docs', '/api-docs']

  // Relax CSP for Swagger UI routes so that scripts/styles load alongside Helmet
  app.use(docPaths, (_req: Request, res: Response, next) => {
    res.setHeader(
      'Content-Security-Policy',
      "default-src 'self'; script-src 'self' 'unsafe-inline' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' https: data:;",
    )
    next()
  })

  // Serve raw OpenAPI JSON spec
  const sendSpec = (_req: Request, res: Response) => {
    res.setHeader('Content-Type', 'application/json')
    res.status(200).send(swaggerSpec)
  }

  app.get('/docs.json', sendSpec)
  app.get('/api-docs.json', sendSpec)
  app.get('/docs/json', sendSpec)

  const uiOptions = {
    customCss: customSwaggerCss,
    customSiteTitle: 'StockPros API Documentation',
    swaggerOptions: {
      persistAuthorization: true,
      displayRequestDuration: true,
      filter: true,
      tagsSorter: 'alpha',
    },
  }

  // Mount Swagger UI on /docs and /api-docs
  app.use('/docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec, uiOptions))
  app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec, uiOptions))
}
