# Repository Guidelines for AI Agents

## Core Principles & Engineering Standards
- **Strict Type Safety & Runtime Validation:** Avoid using untyped data, implicit coercions, or unsafe casts. Enforce explicit static types across all layers and require schema validation for incoming API payloads, route parameters, and environment variables.
- **Explicit Enums & Domain Constants:** Use language-native enums, strict value objects, or schema-enforced enumerations for any fixed set of options, states, roles, or event types. Magic strings or bare numbers for conditional logic are strictly prohibited.
- **API Specification & Documentation Consistency:** When creating, updating, or modifying API endpoints, environment variables, setup commands, or architectural modules, continuously update the corresponding OpenAPI/Swagger specs and repository `README.md` to prevent documentation drift.
- **SonarQube Quality Standards:** Maintain Clean Code attributes (Intentional, Consistent, Adaptable, Responsible). Zero tolerance for security vulnerabilities, bugs, cognitive complexity smells, or duplicated code blocks.
- **Formatting & Style:** Enforce automated formatting (e.g., Prettier) on all modified files. Keep code styles, naming conventions, and file structures completely consistent across the repository.
- **Lean Codebase & Cleanup:** Continuously remove dead code, unused imports, redundant variables, and unreferenced assets. Keep pull requests minimal and focused.
- **Directory Consistency:** Respect and adhere to the established project folder hierarchy. Do not invent duplicate directories, arbitrary subfolders, or place files out of their domain context.

## Strict System & Security Rules
1. **Defensive Runtime Asset Checks:** Always verify the existence of dynamic or external assets (e.g., generated Swagger JSON files, static artifacts) using `fs.existsSync` before attempting to read, import, or parse them at runtime to prevent process boot crashes.
2. **Environment Feature Gating:** Guard developer-only endpoints (e.g., Swagger UI), internal utilities, and debug interfaces behind environment configuration flags or explicit non-production environment checks.
3. **Secrets vs. Application Configuration Isolation:** Ensure only sensitive variables and secret credentials (e.g., API keys, database passwords, private keys) are defined in environment (`.env`) files. Place non-sensitive runtime options, defaults, feature toggles, and static application metadata into dedicated configuration files within the codebase.
4. **Structured Logging & PII Redaction:** Use structured loggers (e.g., Pino) for all operational, error, and audit events. NEVER write or log raw credentials, authorization tokens, passwords, API keys, or personally identifiable information (PII) to system logs or external telemetry streams. Use automated redaction or explicit sanitization.
5. **Audit Data Retention vs. PII Purging:** When executing account or entity deletion routines, purge or anonymize personal identity data from primary databases while maintaining immutable, non-PII system audit logs (`user_id` references only) for operational integrity.
6. **Resource Safety & Non-Blocking Execution:** Avoid unhandled synchronous loops, memory-intensive background tasks, or blocking operations that could exhaust system CPU/RAM bounds.
7. **Single Sign-In Gate & Tenant Isolation:** Every code path that proves an identity or creates a session, whatever the method and including any added in future, must go through the one shared sign-in gate and the one shared session-creation routine, so a tenant's sign-in policy can never be bypassed; never build a parallel path. An identity vouched for by an external provider must be bound to the tenant that provider belongs to, because whoever controls a provider's settings can assert any identity it is allowed to. Switching on anything that decides who may assert an identity is restricted to the tenant's highest role, and changing those settings must return it to the safe (off) state until that role re-approves. Every tenant-scoped route must be covered by the tenant-isolation test suite, and tenant-scoped queries must filter on the tenant explicitly.

## Automated Self-Review & Quality Checklist
Before marking any task or code generation as complete:
1. **Auto-Review Code & Documentation:** Perform a thorough sanity review of all diffs to ensure no unintended breaking changes, schema discrepancies, or regression vulnerabilities were introduced. Verify that the `README.md` and API docs reflect any new environment variables, setup steps, or route additions.
2. **Test Suite Execution & Coverage:** Update existing unit/integration tests or write new tests for modified features. Ensure the test suite passes without regressions. Coverage is enforced via `backend/jest.config.js`'s `coverageThreshold` — a flat 90% quality bar on statements/branches/functions/lines, enforced repo-wide (reached 2026-09-29; the per-file allowlist that got it there has been retired now that the aggregate itself clears 90%). Never lower this threshold to force a failing suite to pass; if a change legitimately drops coverage, add real tests instead.
3. **Static Analysis, Type Verification & Build:** Confirm that type checks (`tsc --noEmit`), build execution (`npm run build`), linter runs (`npm run lint`), module boundary checks (`scripts/check-module-boundaries.cjs`), and Clean Code complexity rules pass with zero errors. New/changed code is additionally gated in CI via SonarCloud (see `sonar-project.properties`), which evaluates only new code against the default Quality Gate (coverage, duplication, maintainability/reliability/security ratings) — it does not require fixing the existing repo-wide issue backlog, so don't treat that backlog as in scope for an unrelated change.
4. **Preserve Error & Log Standards:** Ensure newly introduced routes, functions, or modules maintain the repository's standard error handling, Zod validation errors, and sanitization layers.