// utils/portfolioReport.ts
// Shared presentation layer for portfolio health report exports (CSV + PDF).
// Every value comes straight from the backend /api/v1/decision-support
// responses — nothing here is derived or fabricated client-side.
import type {
    DetailedDecision,
    OverviewDecision,
    PortfolioData,
} from '../types';

export interface PortfolioReportRow {
  symbol: string;
  sector: string;
  quantity: number;
  entryPrice: number;
  currentPrice: number;
  marketValue: number;
  unrealizedPnL: number;
  roiPercent: number;
  marketDecision: string;
  portfolioDecision: string;
  confidence: number | null;
  riskLevel: string;
  reasoningSummary: string;
  riskFlags: string[];
  positionExposurePercent: number | null;
  sectorExposurePercent: number | null;
  overExposed: boolean;
  strategy: { add: boolean; hold: boolean; trim: boolean; exit: boolean } | null;
  holdDuration: string;
  takeProfitZone: string;
  stopLossZone: string;
  watchFor: string[];
}

const currencyFormatter = new Intl.NumberFormat('en-US', {
  style: 'currency',
  currency: 'USD',
  minimumFractionDigits: 2,
  maximumFractionDigits: 2,
});

export const formatCurrency = (value: number): string => currencyFormatter.format(value);

export const formatSignedCurrency = (value: number): string =>
  `${value >= 0 ? '+' : '-'}${currencyFormatter.format(Math.abs(value))}`;

export const formatGeneratedAt = (): string =>
  new Date().toLocaleString('en-US', { dateStyle: 'long', timeStyle: 'short', timeZone: 'Asia/Karachi' });

export const computeRiskProfileLabel = (decisions: OverviewDecision[]): string => {
  if (decisions.length === 0) return 'Not Assessed';
  const highCount = decisions.filter((d) => d.riskLevel === 'HIGH').length;
  const ratio = highCount / decisions.length;
  if (ratio >= 0.6) return 'Aggressive';
  if (ratio >= 0.3) return 'Moderate';
  return 'Conservative';
};

export const buildReportRows = (
  portfolioData: PortfolioData,
  detailedPositions: DetailedDecision[],
): PortfolioReportRow[] =>
  (portfolioData.positions ?? []).map((position) => {
    const detail = detailedPositions.find((dd) => dd.symbol === position.symbol);
    return {
      symbol: position.symbol,
      sector: detail?.sector || position.sector || '—',
      quantity: position.quantity,
      entryPrice: position.avg_entry_price,
      currentPrice: position.currentPrice,
      marketValue: position.currentValue,
      unrealizedPnL: position.unrealizedPnL,
      roiPercent: position.unrealizedPnLPercent,
      marketDecision: detail?.marketDecision ?? '—',
      portfolioDecision: detail?.portfolioDecision ?? '—',
      confidence: detail?.confidence ?? null,
      riskLevel: detail?.riskLevel ?? '—',
      reasoningSummary: detail?.reasoning?.summary ?? '',
      riskFlags: detail?.reasoning?.details ?? [],
      positionExposurePercent: detail?.exposure?.positionPercent ?? null,
      sectorExposurePercent: detail?.exposure?.sectorPercent ?? null,
      overExposed: detail?.exposure?.isOverExposed ?? false,
      strategy: detail?.actionGuidance?.positionStrategy ?? null,
      holdDuration: detail?.actionGuidance?.holdDuration ?? '',
      takeProfitZone: detail?.actionGuidance?.takeProfitZone ?? '',
      stopLossZone: detail?.actionGuidance?.stopLossZone ?? '',
      watchFor: detail?.actionGuidance?.watchFor ?? [],
    };
  });

export const formatConfidence = (confidence: number | null): string =>
  confidence != null ? `${(confidence * 100).toFixed(0)}%` : '—';

export const formatEnabledStrategies = (row: PortfolioReportRow): string => {
  if (!row.strategy) return '—';
  const enabled = Object.entries(row.strategy)
    .filter(([, enabled]) => enabled)
    .map(([key]) => key.toUpperCase());
  return enabled.length > 0 ? enabled.join(' / ') : '—';
};

export const getReportFileName = (extension: 'csv' | 'pdf'): string =>
  `stockpros_portfolio_health_${new Date().toISOString().split('T')[0]}.${extension}`;

export const PORTFOLIO_DISCLAIMER =
  'Portfolio analysis is generated by AI models based on position data, market signals and technical indicators. ' +
  'This report is for informational purposes only and does not constitute financial advice.';
