// utils/forecastExport.ts
// Shared presentation layer for forecast exports (CSV + PDF).
// All values come straight from the backend /api/v1/forecast response —
// nothing here is derived or fabricated client-side.
import { ForecastData } from '../types';

export interface SummaryField {
  label: string;
  value: string;
}

export interface ForecastRow {
  date: string;
  type: 'historical' | 'forecast';
  typeLabel: string;
  base: number;
  bull?: number;
  bear?: number;
}

export const TABLE_COLUMNS = ['Date', 'Base Price', 'Bull Scenario', 'Bear Scenario'];

const currencyFormatter = new Intl.NumberFormat('en-US', {
  style: 'currency',
  currency: 'USD',
  minimumFractionDigits: 2,
  maximumFractionDigits: 2,
});

export const formatCurrency = (value: number): string => currencyFormatter.format(value);

export const formatDate = (dateString: string): string =>
  new Date(dateString).toLocaleDateString('en-US', {
    weekday: 'short',
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    timeZone: 'Asia/Karachi',
  });

export const formatGeneratedAt = (): string =>
  new Date().toLocaleString('en-US', { dateStyle: 'long', timeStyle: 'short', timeZone: 'Asia/Karachi' });

export const getSummaryFields = (data: ForecastData): SummaryField[] => {
  const fields: SummaryField[] = [
    { label: 'Symbol', value: data.symbol },
    { label: 'Forecast Period', value: data.period === '1d' ? '1 Day' : '1 Week' },
  ];

  if (typeof data.currentPrice === 'number') {
    fields.push({ label: 'Current Price', value: formatCurrency(data.currentPrice) });
  }

  if (data.targetRange) {
    fields.push(
      { label: 'Bull Target', value: formatCurrency(data.targetRange.bull) },
      { label: 'Base Target', value: formatCurrency(data.targetRange.base) },
      { label: 'Bear Target', value: formatCurrency(data.targetRange.bear) },
      { label: 'ATR', value: formatCurrency(data.targetRange.atr) },
      { label: 'Range Confidence', value: data.targetRange.confidence },
    );
  }

  return fields;
};

export const getTableRows = (data: ForecastData): ForecastRow[] => {
  return (data.predictions || []).map((p, index) => ({
    date: formatDate(p.date),
    type: 'forecast' as const,
    typeLabel: `Forecast Day ${index + 1}`,
    base: p.base,
    bull: p.bull,
    bear: p.bear,
  }));
};

export const getReportFileName = (data: ForecastData, extension: 'csv' | 'pdf'): string =>
  `stockpros_forecast_${data.symbol}_${data.period}_${new Date().toISOString().split('T')[0]}.${extension}`;

export const DISCLAIMER =
  'Predictions are generated by AI models based on historical price patterns and technical indicators. ' +
  'This report is for informational and educational purposes only and does not constitute personalized financial, legal, tax, or fiduciary advice.';
